version: "3.7"
services:
  ubuntu:
    container_name: ubuntu
    build:
      context: .
      args:
        UBUNTU_VERSION: $UBUNTU_VERSION
    environment: 
      - TZ=Asia/Kolkata
    stdin_open: true
    tty: true    